### ISSUE TITLE
Bug: Popup left arrow shifting

### ISSUE THREAD

**Issue by selicens** [lio-mengxiang/mx-design#1]
![image](https://github.com/lio-mengxiang/mx-design/assets/69418751/ae264e7c-86b5-42b8-9769-01799b8f8057)
popup left arrow，弹出层左侧时箭头偏移
![image](https://github.com/lio-mengxiang/mx-design/assets/69418751/a4ae7b30-37a7-4a58-a3e9-645ac90f26d0)
tootilp left arrow，底层也是使用的popup，算同一个bug

**Comment by lio-mengxiang** [comment]
感谢提出，这个会在今天修复

**Comment by lio-mengxiang** [comment]
已修复
