### ISSUE TITLE
提个小问题，logo在暗黑模式下展示不是很完全

### ISSUE THREAD

**Issue by XueMeijing** [lio-mengxiang/mx-design#10]
![image](https://github.com/lio-mengxiang/mx-design/assets/35559153/f4cea032-435c-4502-93aa-288daf8dfcd1)
![image](https://github.com/lio-mengxiang/mx-design/assets/35559153/6aa5647b-e6eb-41f5-a113-69f433d516eb)

**Comment by lio-mengxiang** [comment]
非常感谢你提出问题，你是用的chrome商店里的暗色主题吗？

**Comment by lio-mengxiang** [comment]
非常感谢你的问题，我会在今天晚点回家解决，感谢你的关注，也随时欢迎一起交流react 组件库的问题😁

**Comment by lio-mengxiang** [comment]
> ![image](https://user-images.githubusercontent.com/35559153/259707044-f4cea032-435c-4502-93aa-288daf8dfcd1.png) ![image](https://user-images.githubusercontent.com/35559153/259707099-6aa5647b-e6eb-41f5-a113-69f433d516eb.png)

本来昨天晚上能修好的，mac用到一半突然卡死然后不停重启，现在正在修电脑的路上，哎

**Comment by XueMeijing** [comment]
> 本来昨天晚上能修好的，mac用到一半突然卡死然后不停重启，现在正在修电脑的路上，哎

你这也太惨了吧@@ 是github -> 设置 -> 外观 里面的暗黑主题，有点类似antd字体的设计，尽量保证下对比度。可以参考下antd react 啥的logo，都是鲜艳的颜色

![image](https://github.com/lio-mengxiang/mx-design/assets/35559153/f3e3ab8f-3f27-431a-9aac-6067d6d05a5d)

**Comment by lio-mengxiang** [comment]
> > 本来昨天晚上能修好的，mac用到一半突然卡死然后不停重启，现在正在修电脑的路上，哎
> 
> 你这也太惨了吧@@ 是github -> 设置 -> 外观 里面的暗黑主题，有点类似antd字体的设计，尽量保证下对比度。可以参考下antd react 啥的logo，都是鲜艳的颜色
> 
> ![image](https://user-images.githubusercontent.com/35559153/259916039-f3e3ab8f-3f27-431a-9aac-6067d6d05a5d.png)

是的，因为是图片，

> > 本来昨天晚上能修好的，mac用到一半突然卡死然后不停重启，现在正在修电脑的路上，哎
> 
> 你这也太惨了吧@@ 是github -> 设置 -> 外观 里面的暗黑主题，有点类似antd字体的设计，尽量保证下对比度。可以参考下antd react 啥的logo，都是鲜艳的颜色
> 
> ![image](https://user-images.githubusercontent.com/35559153/259916039-f3e3ab8f-3f27-431a-9aac-6067d6d05a5d.png)

是的，很惨，我的mac主板坏了，这个问题已解决，在github里有特定语法设置在暗黑模式选择不同的图片
