### ISSUE TITLE
Popup组件箭头有多余圆角边框

### ISSUE THREAD

**Issue by WhiteWatson** [lio-mengxiang/mx-design#11]
![image](https://github.com/lio-mengxiang/mx-design/assets/48992972/9a601be1-11f0-4aad-905d-74322fbbf722)

**Comment by lio-mengxiang** [comment]
非常感谢您的issue，目前准备先把所有中文教程上到官网，会跟这个bug修复一起发版

**Comment by lio-mengxiang** [comment]
> ![image](https://user-images.githubusercontent.com/48992972/261173526-9a601be1-11f0-4aad-905d-74322fbbf722.png)

非常感谢你的issue，我正在准备先把目前写好的中文教程移到官网里，会跟这个bug修复一起上

**Comment by lio-mengxiang** [comment]
这个bug已经修复，因为涉及到css样式的全面改动，以前用shadow去实现的，现在改为了border，也是为后续dropdown组件的样式做铺垫，所以没有采用你的pr，请谅解
